language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install:
  - travis_retry composer install --no-interaction --optimize-autoloader --prefer-source

script:
  - vendor/bin/phpunit --exclude-group exclude-from-travis
  - vendor/bin/phpcs --standard=PSR2 src/ bin/ hooks/ tests/
